//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MyBusiness.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db_9ae46c_myblogEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db_9ae46c_myblogEntities object using the connection string found in the 'db_9ae46c_myblogEntities' section of the application configuration file.
        /// </summary>
        public db_9ae46c_myblogEntities() : base("name=db_9ae46c_myblogEntities", "db_9ae46c_myblogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_9ae46c_myblogEntities object.
        /// </summary>
        public db_9ae46c_myblogEntities(string connectionString) : base(connectionString, "db_9ae46c_myblogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_9ae46c_myblogEntities object.
        /// </summary>
        public db_9ae46c_myblogEntities(EntityConnection connection) : base(connection, "db_9ae46c_myblogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mybusiness_categories> mybusiness_categories
        {
            get
            {
                if ((_mybusiness_categories == null))
                {
                    _mybusiness_categories = base.CreateObjectSet<mybusiness_categories>("mybusiness_categories");
                }
                return _mybusiness_categories;
            }
        }
        private ObjectSet<mybusiness_categories> _mybusiness_categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mybusiness_images> mybusiness_images
        {
            get
            {
                if ((_mybusiness_images == null))
                {
                    _mybusiness_images = base.CreateObjectSet<mybusiness_images>("mybusiness_images");
                }
                return _mybusiness_images;
            }
        }
        private ObjectSet<mybusiness_images> _mybusiness_images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<systemuser> systemusers
        {
            get
            {
                if ((_systemusers == null))
                {
                    _systemusers = base.CreateObjectSet<systemuser>("systemusers");
                }
                return _systemusers;
            }
        }
        private ObjectSet<systemuser> _systemusers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mybusiness_categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomybusiness_categories(mybusiness_categories mybusiness_categories)
        {
            base.AddObject("mybusiness_categories", mybusiness_categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mybusiness_images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomybusiness_images(mybusiness_images mybusiness_images)
        {
            base.AddObject("mybusiness_images", mybusiness_images);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the systemusers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosystemusers(systemuser systemuser)
        {
            base.AddObject("systemusers", systemuser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_9ae46c_myblogModel", Name="mybusiness_categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mybusiness_categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mybusiness_categories object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static mybusiness_categories Createmybusiness_categories(global::System.String id)
        {
            mybusiness_categories mybusiness_categories = new mybusiness_categories();
            mybusiness_categories.id = id;
            return mybusiness_categories;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_9ae46c_myblogModel", Name="mybusiness_images")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mybusiness_images : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mybusiness_images object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="filename">Initial value of the filename property.</param>
        /// <param name="length">Initial value of the length property.</param>
        public static mybusiness_images Createmybusiness_images(global::System.Int32 id, global::System.String filename, global::System.Int32 length)
        {
            mybusiness_images mybusiness_images = new mybusiness_images();
            mybusiness_images.id = id;
            mybusiness_images.filename = filename;
            mybusiness_images.length = length;
            return mybusiness_images;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String filename
        {
            get
            {
                return _filename;
            }
            set
            {
                if (_filename != value)
                {
                    OnfilenameChanging(value);
                    ReportPropertyChanging("filename");
                    _filename = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("filename");
                    OnfilenameChanged();
                }
            }
        }
        private global::System.String _filename;
        partial void OnfilenameChanging(global::System.String value);
        partial void OnfilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String folder
        {
            get
            {
                return _folder;
            }
            set
            {
                OnfolderChanging(value);
                ReportPropertyChanging("folder");
                _folder = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("folder");
                OnfolderChanged();
            }
        }
        private global::System.String _folder;
        partial void OnfolderChanging(global::System.String value);
        partial void OnfolderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 length
        {
            get
            {
                return _length;
            }
            set
            {
                if (_length != value)
                {
                    OnlengthChanging(value);
                    ReportPropertyChanging("length");
                    _length = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("length");
                    OnlengthChanged();
                }
            }
        }
        private global::System.Int32 _length;
        partial void OnlengthChanging(global::System.Int32 value);
        partial void OnlengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hidden
        {
            get
            {
                return _hidden;
            }
            set
            {
                OnhiddenChanging(value);
                ReportPropertyChanging("hidden");
                _hidden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hidden");
                OnhiddenChanged();
            }
        }
        private Nullable<global::System.Int32> _hidden;
        partial void OnhiddenChanging(Nullable<global::System.Int32> value);
        partial void OnhiddenChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_9ae46c_myblogModel", Name="systemuser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class systemuser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new systemuser object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="passwordSalt">Initial value of the PasswordSalt property.</param>
        public static systemuser Createsystemuser(global::System.Int32 id, global::System.String userID, global::System.String email, global::System.String password, global::System.String passwordSalt)
        {
            systemuser systemuser = new systemuser();
            systemuser.id = id;
            systemuser.UserID = userID;
            systemuser.Email = email;
            systemuser.Password = password;
            systemuser.PasswordSalt = passwordSalt;
            return systemuser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PasswordSalt
        {
            get
            {
                return _PasswordSalt;
            }
            set
            {
                OnPasswordSaltChanging(value);
                ReportPropertyChanging("PasswordSalt");
                _PasswordSalt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordSalt");
                OnPasswordSaltChanged();
            }
        }
        private global::System.String _PasswordSalt;
        partial void OnPasswordSaltChanging(global::System.String value);
        partial void OnPasswordSaltChanged();

        #endregion

    
    }

    #endregion

    
}
